# Generated by Django 5.0.6 on 2026-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars_balance',
            field=models.PositiveIntegerField(default=5, help_text='Stars to trade — earn by publishing, spend to download'),
        ),
    ]
