# Generated by Django 6.1 on 2026-08-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False)),
                ('clamav_enabled', models.BooleanField(default=True)),
                ('r2_enabled', models.BooleanField(default=True)),
                ('search_enabled', models.BooleanField(default=True)),
                ('pwa_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_forks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_prs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_trading',
            field=models.BooleanField(default=True, help_text='If off, your vibes are free (0 ★)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_language',
            field=models.BooleanField(default=True, help_text='Auto detect language % from ZIP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_thumbnail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_trade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nolo_enabled',
            field=models.BooleanField(default=True, help_text='Nolo auto-review on upload'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_language',
            field=models.BooleanField(default=True),
        ),
    ]
