# Generated by Django 6.1 on 2026-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sitesettings_profile_allow_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro plan — can see who viewed your vibes, AI README, money'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
