# Generated by Django 5.0.6 on 2026-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_stars_balance_gte_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='auto_run_enabled',
            field=models.BooleanField(default=False, help_text='If On, open the file preview after publish. This is not a Docker host.'),
        ),
    ]
