# Generated by Django 5.0.6 on 2026-08-14 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_sitesettings_auto_run_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stars_balance',
            field=models.PositiveIntegerField(default=0, help_text='Stars to trade — verify your email for the welcome grant, earn more when people trade your vibes'),
        ),
        migrations.CreateModel(
            name='StarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('welcome', 'Welcome grant'), ('trade_spend', 'Trade — stars spent'), ('trade_earn', 'Trade — stars earned'), ('challenge_bounty', 'Challenge bounty'), ('admin_adjust', 'Admin adjustment'), ('backfill', 'Ledger backfill')], max_length=20)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_stare_user_id_02b749_idx')],
            },
        ),
    ]
