# Generated by Django 5.2.17 on 2026-08-17 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_starevent_reason_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='starevent',
            name='reason',
            field=models.CharField(choices=[('welcome', 'Welcome grant'), ('trade_spend', 'Trade — stars spent'), ('trade_earn', 'Trade — stars earned'), ('tip_spend', 'Tip — stars sent'), ('tip_earn', 'Tip — stars received'), ('challenge_bounty', 'Challenge bounty'), ('admin_adjust', 'Admin adjustment'), ('backfill', 'Ledger backfill'), ('payout_hold', 'Payout — stars held for cash-out'), ('payout_refund', 'Payout — rejected, stars returned')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_stars', models.PositiveIntegerField(help_text='Stars held from the wallet at request time')),
                ('amount_zar', models.PositiveIntegerField(help_text='ZAR frozen at request — the quoted amount')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('holder_name', models.CharField(max_length=80)),
                ('admin_note', models.CharField(blank=True, help_text='EFT reference or rejection reason', max_length=200)),
                ('provider_ref', models.CharField(blank=True, help_text='Paystack transfer code when a transfer was initiated', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='users_payou_status_8a94a6_idx'), models.Index(fields=['user', '-created_at'], name='users_payou_user_id_94177e_idx')],
            },
        ),
    ]
