# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_last_rename_at_profile_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_persona',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
