# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_notify_on_comment_profile_notify_on_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='admin@blaqvibes.co.za', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_github_label',
            field=models.CharField(blank=True, default='GitHub @Njwacky', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_github_url',
            field=models.URLField(blank=True, default='https://github.com/Njwacky'),
        ),
    ]
