# Generated by Django 5.2.17 on 2026-09-10 07:58

import users.footer_contacts
from django.db import migrations, models
from urllib.parse import urlparse


def seed_footer_contacts(apps, schema_editor):
    """Move the three legacy SiteSettings fields into rows.

    The footer contact list became data, so an installation that already
    published an email and a GitHub link must keep publishing them — an
    operator should see the same footer after `migrate` as before it, now as
    rows they can add to. Runs before the legacy columns are dropped (next
    migration), and creates nothing if rows already exist.
    """
    FooterContact = apps.get_model('users', 'FooterContact')
    SiteSettings = apps.get_model('users', 'SiteSettings')
    if FooterContact.objects.exists():
        return

    site = SiteSettings.objects.order_by('pk').first()
    if site is None:
        # A brand-new database: seed the same public defaults the old
        # SiteSettings fields had, so the footer is not silently empty.
        rows = [
            ('email', 'admin@blaqvibes.co.za', ''),
            ('github', 'Njwacky', 'GitHub @Njwacky'),
        ]
    else:
        rows = []
        if getattr(site, 'footer_contact_email', ''):
            rows.append(('email', site.footer_contact_email.lower(), ''))
        url = (getattr(site, 'footer_github_url', '') or '').strip()
        if url:
            # Keep the path an operator already published — a user profile
            # (`/Njwacky`) or a repository (`/Njwacky/blaqVibe`) — instead of
            # silently shortening it to the first segment. Handles allow two
            # segments; anything deeper falls back to a plain link.
            segments = [part for part in urlparse(url).path.strip('/').split('/') if part]
            handle = '/'.join(segments[:2]) if len(segments) <= 2 else ''
            if handle:
                rows.append(('github', handle, getattr(site, 'footer_github_label', '') or ''))
            else:
                # The URL pointed at a bare host: keep it as a link rather
                # than inventing a handle from it.
                rows.append(('website', url, getattr(site, 'footer_github_label', '') or ''))

    for position, (kind, value, label) in enumerate(rows):
        FooterContact.objects.create(
            kind=kind,
            value=value,
            label=label,
            position=position * 10,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_sitesettings_footer_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=users.footer_contacts.contact_kind_choices, default='email', max_length=24)),
                ('value', models.CharField(help_text='The address, number, handle or URL — never a full link you type by hand.', max_length=200)),
                ('label', models.CharField(blank=True, help_text='Optional. What visitors read instead of the raw address, number or handle.', max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer contact',
                'verbose_name_plural': 'footer contacts',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RunPython(seed_footer_contacts, migrations.RunPython.noop),
    ]
