# Generated by Django 5.2.17 on 2026-09-10 07:58

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the three fixed footer fields.

    Safe only because 0023 copied their values into FooterContact rows first:
    one email field and one GitHub URL field cannot express "two support
    mailboxes and a WhatsApp number", and leaving them behind would give the
    footer two sources of truth.
    """

    dependencies = [
        ('users', '0023_footercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_github_label',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_github_url',
        ),
    ]
