# Generated by Django 5.2.17 on 2026-09-17 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_pg_trgm_user_search_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('offensive_language', 'Offensive language'), ('harassment', 'Harassment / abuse'), ('spam', 'Spam / flooding'), ('impersonation', 'Impersonation'), ('other', 'Other rule breach')], default='other', max_length=24)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('source', models.CharField(choices=[('auto', 'Automatic — rule violation'), ('staff', 'Staff decision')], default='auto', max_length=10)),
                ('days', models.PositiveSmallIntegerField(default=30)),
                ('strike_count', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_note', models.CharField(blank=True, max_length=300)),
                ('imposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantines_imposed', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantines_lifted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open — awaiting staff'), ('accepted', 'Accepted — quarantine lifted'), ('denied', 'Denied — quarantine stands')], db_index=True, default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_appeals', to=settings.AUTH_USER_MODEL)),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='users.userquarantine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offensive_language', 'Offensive language'), ('harassment', 'Harassment / abuse'), ('spam', 'Spam / flooding'), ('impersonation', 'Impersonation'), ('other', 'Other rule breach')], db_index=True, default='other', max_length=24)),
                ('surface', models.CharField(blank=True, max_length=24)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('evidence', models.TextField(blank=True)),
                ('project_slug', models.CharField(blank=True, max_length=120)),
                ('quarantined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_rulev_user_id_14a7a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userquarantine',
            index=models.Index(fields=['user', 'status', '-started_at'], name='users_userq_user_id_9c07da_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantineappeal',
            index=models.Index(fields=['status', 'created_at'], name='users_quara_status_ff27d6_idx'),
        ),
    ]
