# Generated by Django 5.2.17 on 2026-09-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userquarantine_quarantineappeal_ruleviolation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open — waiting on the team'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('last_user_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admin_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_user_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_staff', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.feedbackthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackthread',
            index=models.Index(fields=['status', 'last_user_message_at'], name='users_feedb_status_886ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['thread', 'created_at'], name='users_feedb_thread__03bd48_idx'),
        ),
    ]
