# Generated by Django 5.2.17 on 2026-09-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_feedbackthread_feedbackmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name — e.g. Portfolio, Blog, Side project', max_length=60)),
                ('url', models.URLField(max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under maintenance'), ('inactive', 'Inactive'), ('moved', 'Moved')], default='active', max_length=12)),
                ('moved_to', models.URLField(blank=True, help_text='Only for Moved — where the site lives now', max_length=300)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='users.profile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='profilelink_label_nonempty')],
            },
        ),
    ]
