# Generated by Django 5.2.17 on 2026-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_profilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='overlay_seen',
            field=models.BooleanField(default=False, help_text='True once the first-time welcome overlay has been completed or skipped'),
        ),
    ]
