# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_overlay_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_feedback_fab',
            field=models.BooleanField(default=True, help_text='Show the floating feedback shortcut'),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/'),
        ),
    ]
