# Generated by Django 5.2.17 on 2026-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profile_show_feedback_fab_feedbackmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feedback_fab_tip_dismissed',
            field=models.BooleanField(default=False, help_text='True once the user has dismissed the feedback floating action button tip'),
        ),
    ]
