# Generated by Django 5.0.6 on 2026-08-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('quarantined', 'Quarantined'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='appproject',
            name='gallery_app_categor_4c5014_idx',
        ),
        migrations.AddField(
            model_name='appproject',
            name='scan_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Scan/Review'), ('published', 'Published'), ('quarantined', 'Quarantined — Virus/Secret')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='appproject',
            index=models.Index(fields=['status'], name='gallery_app_status_e9cdd1_idx'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_job', to='gallery.appproject'),
        ),
    ]
