# Generated by Django 5.0.6 on 2026-08-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_scanjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreport',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='appreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gallery.appproject'),
        ),
        migrations.AlterField(
            model_name='appreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('malware', 'Malware/Virus'), ('copyright', 'Copyright'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('zip_file', models.FileField(upload_to='apps/versions/')),
                ('changelog', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gallery.appproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
