# Generated by Django 5.0.6 on 2026-08-08 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_appreport_details_alter_appreport_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='language_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appproject',
            name='star_cost',
            field=models.PositiveIntegerField(default=0, help_text='Stars to trade to download (0=free, 1=Bronze, 3=Silver, 5=Gold)'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_bought', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='gallery.appproject')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sold', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('buyer', 'project')},
            },
        ),
    ]
