# Generated by Django 6.1 on 2026-08-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_appproject_avg_rating_appproject_review_count_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='gallery.appproject'),
        ),
    ]
