# Generated by Django 5.0.6 on 2026-08-08 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_appproject_ai_readme_appproject_price_zar_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_a', models.PositiveIntegerField(default=0)),
                ('votes_b', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vibe_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_a', to='gallery.appproject')),
                ('vibe_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_b', to='gallery.appproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes', to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gallery.vibebattle')),
            ],
            options={
                'unique_together': {('user', 'battle')},
            },
        ),
    ]
