# Generated by Django 5.0.6 on 2026-08-14 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_harden_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='project',
        ),
        migrations.RemoveIndex(
            model_name='paymentintent',
            name='gallery_pay_buyer_p_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='gallery_pay_referen_8ad3fd_idx',
            old_name='gallery_pay_referen_idx',
        ),
        migrations.AlterField(
            model_name='appproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Scan/Review'), ('published', 'Published'), ('quarantined', 'Quarantined — Virus/Secret'), ('removed', 'Removed — buyers keep access')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow'), ('trade', 'Trade'), ('sale', 'Sale'), ('pr', 'Pull request'), ('published', 'Published'), ('quarantined', 'Quarantined'), ('review', 'Review'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gallery.appproject'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='gallery.appproject'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['buyer', 'project', 'status'], name='gallery_pay_buyer_i_ec3c76_idx'),
        ),
        migrations.DeleteModel(
            name='Deploy',
        ),
    ]
