# Generated by Django 5.2.17 on 2026-08-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_star_ledger_and_paid_record_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KindAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('game', 'Game'), ('web_app', 'Web app'), ('static_site', 'Website'), ('api_backend', 'API / backend'), ('mobile_app', 'Mobile app'), ('desktop_app', 'Desktop app'), ('ai_ml', 'AI / ML'), ('bot', 'Bot / automation'), ('data_viz', 'Data / dashboard'), ('cli_tool', 'CLI / script'), ('library', 'Library / SDK'), ('extension', 'Browser extension'), ('template', 'Template / UI kit'), ('other', 'Other')], max_length=20)),
                ('score', models.FloatField(default=0)),
                ('events', models.PositiveIntegerField(default=0)),
                ('last_event', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='appproject',
            name='appeal_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='appproject',
            name='appeal_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appproject',
            name='creator_kind',
            field=models.CharField(blank=True, choices=[('', 'Auto-detect (recommended)'), ('game', 'Game'), ('web_app', 'Web app'), ('static_site', 'Website'), ('api_backend', 'API / backend'), ('mobile_app', 'Mobile app'), ('desktop_app', 'Desktop app'), ('ai_ml', 'AI / ML'), ('bot', 'Bot / automation'), ('data_viz', 'Data / dashboard'), ('cli_tool', 'CLI / script'), ('library', 'Library / SDK'), ('extension', 'Browser extension'), ('template', 'Template / UI kit'), ('other', 'Other')], default='', help_text="Creator's own pick. Blank = trust auto-detection.", max_length=20),
        ),
        migrations.AddField(
            model_name='appproject',
            name='kind',
            field=models.CharField(choices=[('game', 'Game'), ('web_app', 'Web app'), ('static_site', 'Website'), ('api_backend', 'API / backend'), ('mobile_app', 'Mobile app'), ('desktop_app', 'Desktop app'), ('ai_ml', 'AI / ML'), ('bot', 'Bot / automation'), ('data_viz', 'Data / dashboard'), ('cli_tool', 'CLI / script'), ('library', 'Library / SDK'), ('extension', 'Browser extension'), ('template', 'Template / UI kit'), ('other', 'Other')], db_index=True, default='other', help_text='What sort of program this is — auto-detected, creator can override.', max_length=20),
        ),
        migrations.AddField(
            model_name='appproject',
            name='kind_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appproject',
            name='kind_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appproject',
            name='kind_source',
            field=models.CharField(blank=True, default='', help_text='heuristic | claude | gemini | groq | creator | moderator', max_length=20),
        ),
        migrations.AddField(
            model_name='appproject',
            name='preview_mode',
            field=models.CharField(choices=[('snippet', 'Runs in a sandboxed preview'), ('files', 'File list + README only')], default='files', help_text='snippet = runs in the sandboxed iframe. files = file list + README only.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='appproject',
            index=models.Index(fields=['status', '-appeal_score'], name='gallery_app_status_appeal_idx'),
        ),
        migrations.AddIndex(
            model_name='appproject',
            index=models.Index(fields=['status', 'kind', '-appeal_score'], name='gallery_app_kind_appeal_idx'),
        ),
        migrations.AddField(
            model_name='kindaffinity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kind_affinities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='kindaffinity',
            index=models.Index(fields=['user', '-score'], name='gallery_kin_user_id_d12bb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kindaffinity',
            unique_together={('user', 'kind')},
        ),
    ]
