# Generated by Django 5.2.17 on 2026-08-16 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_backfill_kind_and_appeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow'), ('tip', 'Tip'), ('co_owner', 'Co-owner'), ('trade', 'Trade'), ('sale', 'Sale'), ('pr', 'Pull request'), ('published', 'Published'), ('quarantined', 'Quarantined'), ('review', 'Review'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectCoOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.PositiveSmallIntegerField(help_text='% of star trade revenue (1–100). Owner keeps the remainder.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owners', to='gallery.appproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(check=models.Q(('share_percent__gte', 1), ('share_percent__lte', 100)), name='co_owner_share_between_1_and_100')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
