# Generated by Django 5.2.17 on 2026-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_appproject_trust_trust_graded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='static_entry',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='preview_mode',
            field=models.CharField(choices=[('snippet', 'Runs in a sandboxed preview'), ('static_zip', 'Static site runs in a sandboxed preview'), ('files', 'File list + README only')], default='files', help_text='snippet = inline HTML runs in the sandboxed iframe. static_zip = a static site in the ZIP runs there too. files = file list + README only.', max_length=12),
        ),
    ]
