# Generated by Django 5.2.17 on 2026-09-03 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0028_appreport_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproject',
            name='price_zar',
            field=models.PositiveIntegerField(default=0, help_text='Money price in ZAR (0=free, 50=R50) — max R9999', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='star_cost',
            field=models.PositiveIntegerField(default=0, help_text='Stars to trade to download (0=free … 5=Gold)', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
