# Generated by Django 5.2.17 on 2026-09-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_skill_skilluse'),
        ('gallery', '0030_alter_notification_kind'),
    ]

    operations = [
    ]
