# Generated by Django 5.0.6 on 2026-09-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_merge_20260905_1244'),
        ('gallery', '0031_merge_skills_notifications'),
    ]

    operations = [
    ]
