# Generated by Django 5.2.17 on 2026-09-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_merge_20260905_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibebattle',
            name='battle_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
