# Generated by Django 5.2.17 on 2026-09-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_rename_gallery_skil_is_publ_4d9a1f_idx_gallery_ski_is_publ_62c7b1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('published', 'First publish'), ('version', 'New version'), ('remixed', 'Remixed')], max_length=12)),
                ('label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='gallery_ski_is_publ_62c7b1_idx',
            old_name='gallery_skil_is_publ_4d9a1f_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='gallery_ski_creator_8b0ba2_idx',
            old_name='gallery_skil_creator_3d8e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='skilluse',
            new_name='gallery_ski_skill_i_140ee5_idx',
            old_name='gallery_skil_skill_id_5e4e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='skilluse',
            new_name='gallery_ski_user_id_674f6e_idx',
            old_name='gallery_skil_user_id_8bfc0b_idx',
        ),
        migrations.RenameIndex(
            model_name='skilluse',
            new_name='gallery_ski_project_e48c23_idx',
            old_name='gallery_skil_project_9a8e72_idx',
        ),
        migrations.AddField(
            model_name='projectevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gallery.appproject'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', '-created_at'], name='gallery_pro_project_afa01c_idx'),
        ),
    ]
