# Generated by Django 5.2.17 on 2026-09-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0035_backfill_project_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='First time this project became public. Written by the platform.', null=True),
        ),
        migrations.AddField(
            model_name='appproject',
            name='source_skill',
            field=models.ForeignKey(blank=True, help_text='Builder Skill this project was built from, when one was used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='built_projects', to='gallery.skill'),
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('summary', models.CharField(max_length=260)),
                ('problem', models.TextField(blank=True, max_length=1000)),
                ('workflow', models.TextField(max_length=5000)),
                ('tools', models.CharField(blank=True, max_length=300)),
                ('expected_output', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gallery.skill')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='appproject',
            name='source_skill_version',
            field=models.ForeignKey(blank=True, help_text='The exact skill version used — immutable, so the proof cannot drift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='built_projects', to='gallery.skillversion'),
        ),
        migrations.AddField(
            model_name='skilluse',
            name='skill_version',
            field=models.ForeignKey(blank=True, help_text='The exact version of the skill this builder started from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='gallery.skillversion'),
        ),
        migrations.AddIndex(
            model_name='skillversion',
            index=models.Index(fields=['skill', '-version'], name='gallery_ski_skill_i_58e47b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillversion',
            unique_together={('skill', 'version')},
        ),
    ]
