# Generated by Django 5.2.17 on 2026-09-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_notification_upload_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='ai_got_wrong',
            field=models.CharField(blank=True, default='', help_text='Where AI failed and the builder had to think.', max_length=400),
        ),
        migrations.AddField(
            model_name='appproject',
            name='human_did',
            field=models.CharField(blank=True, default='', help_text='What the human actually did (spec, review, tests, architecture…).', max_length=400),
        ),
        migrations.AddField(
            model_name='appproject',
            name='problem_statement',
            field=models.CharField(blank=True, default='', help_text='What problem this Build tries to solve.', max_length=400),
        ),
        migrations.AddField(
            model_name='appproject',
            name='remix_changed',
            field=models.CharField(blank=True, default='', help_text='If remixed: what this version changed.', max_length=400),
        ),
        migrations.AddField(
            model_name='appproject',
            name='remix_why',
            field=models.CharField(blank=True, default='', help_text='If remixed: why it changed.', max_length=400),
        ),
    ]
