# Generated by Django 5.2.17 on 2026-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0039_proof_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ran_it',
            field=models.BooleanField(default=False, help_text='Reviewer actually ran or opened the files.'),
        ),
        migrations.AddField(
            model_name='review',
            name='readme_clear',
            field=models.BooleanField(default=False, help_text='README was enough to understand the Build.'),
        ),
    ]
