# Generated by Django 5.2.17 on 2026-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0040_review_witness_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='build_choice',
            field=models.CharField(blank=True, choices=[('', 'Derive from evidence'), ('human', 'Human-built'), ('ai_assisted', 'AI-assisted'), ('ai_generated', 'AI-generated')], default='', help_text="Creator's publish-time pick. Blank = derive from evidence.", max_length=20),
        ),
    ]
