# Generated by Django 5.2.17 on 2026-09-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0044_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('critical', 'Critical'), ('action', 'Action needed'), ('money', 'Money'), ('social', 'Social'), ('system', 'System')], db_index=True, default='system', help_text='Severity stripe — see gallery.notify.CATEGORY_OF_KIND. Stored, not derived.', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='reminded_at',
            field=models.DateTimeField(blank=True, help_text='Last time this row was re-delivered as a reminder.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow'), ('tip', 'Tip'), ('co_owner', 'Co-owner'), ('trade', 'Trade'), ('sale', 'Sale'), ('pr', 'Pull request'), ('published', 'Published'), ('quarantined', 'Quarantined'), ('review', 'Review'), ('challenge', 'Challenge'), ('payout', 'Payout'), ('git_push', 'Git push'), ('report', 'Report'), ('upload', 'ZIP upload'), ('star', 'Star'), ('fork', 'Fork'), ('milestone', 'Milestone'), ('achievement', 'Achievement'), ('git_push_rejected', 'Git push rejected'), ('approval', 'Approval needed'), ('pending', 'Pending approval'), ('review_needed', 'Review needed'), ('challenge_draft', 'Challenge draft'), ('role', 'Role'), ('account_quarantine', 'Account quarantine'), ('appeal', 'Quarantine appeal'), ('duplicate', 'Duplicate build'), ('malfunction', 'Malfunction')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttentionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('duplicate', 'Duplicate build'), ('malfunction', 'Malfunction')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Waiting for the owner'), ('decided', 'Keeper chosen — loser parked'), ('deleted', 'Cleaned up'), ('restored', 'Undone — both kept'), ('dismissed', 'Dismissed by the owner')], db_index=True, default='open', max_length=10)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('action', 'Action needed'), ('money', 'Money'), ('social', 'Social'), ('system', 'System')], db_index=True, default='action', max_length=10)),
                ('headline', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('fix_hint', models.CharField(blank=True, help_text='Malfunction only: the concrete repair, in one sentence.', max_length=300)),
                ('pair_key', models.CharField(max_length=64, unique=True)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Backend-only proof: matched signals, similarity score, scan facts.')),
                ('decision_source', models.CharField(blank=True, choices=[('', '—'), ('user', 'You chose'), ('system', 'BlaqVibes chose')], default='', max_length=6)),
                ('rationale', models.TextField(blank=True, help_text='Why THIS keeper — written by gallery.attention.explain_choice, shown verbatim.')),
                ('scores', models.JSONField(blank=True, default=list, help_text='Per-candidate score breakdown behind the rationale (auditable).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When BlaqVibes decides for you (created_at + ATTENTION_DECISION_DAYS).')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='First time the owner saw the decision. Starts the 24h final-delete clock.', null=True)),
                ('final_delete_at', models.DateTimeField(blank=True, db_index=True, help_text='acknowledged_at + ATTENTION_FINAL_DELETE_HOURS — silence after that erases the parked copy.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('remind_count', models.PositiveIntegerField(default=0)),
                ('dismissed_reason', models.CharField(blank=True, choices=[('', '—'), ('not_a_duplicate', 'Not a duplicate — keep both'), ('will_fix', "Keep it — I'll fix it"), ('system_keep', 'BlaqVibes decided it is worth fixing')], default='', max_length=16)),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_kept', to='gallery.appproject')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_subjects', to='gallery.appproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttentionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('', 'Candidate'), ('keeper', 'Keeper'), ('dropped', 'Dropped')], default='', max_length=8)),
                ('score', models.FloatField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Fixed sentences from the keeper strategy — the readable half of the score.')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(blank=True, choices=[('', '—'), ('parked', 'Parked (soft delete — restorable)'), ('deleted', 'Deleted for good'), ('restored', 'Restored'), ('kept', 'Kept — nothing removed')], default='', max_length=10)),
                ('parked_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_candidates', to='gallery.appproject')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='gallery.attentioncase')),
            ],
            options={
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='attention_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gallery.attentioncase'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category', '-created_at'], name='gallery_not_user_id_5d30bd_idx'),
        ),
        migrations.AddIndex(
            model_name='attentioncase',
            index=models.Index(fields=['user', 'status', '-created_at'], name='gallery_att_user_id_4d2452_idx'),
        ),
        migrations.AddIndex(
            model_name='attentioncase',
            index=models.Index(fields=['status', 'expires_at'], name='gallery_att_status_027dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='attentioncase',
            index=models.Index(fields=['status', 'final_delete_at'], name='gallery_att_status_2ebd22_idx'),
        ),
        migrations.AddIndex(
            model_name='attentioncandidate',
            index=models.Index(fields=['case', 'role'], name='gallery_att_case_id_07a3cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='attentioncandidate',
            constraint=models.UniqueConstraint(fields=('case', 'project'), name='one_candidate_row_per_case_project'),
        ),
    ]
