# Generated by Django 5.2.17 on 2026-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0046_backfill_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow'), ('tip', 'Tip'), ('co_owner', 'Co-owner'), ('trade', 'Trade'), ('sale', 'Sale'), ('pr', 'Pull request'), ('published', 'Published'), ('quarantined', 'Quarantined'), ('review', 'Review'), ('challenge', 'Challenge'), ('payout', 'Payout'), ('git_push', 'Git push'), ('report', 'Report'), ('upload', 'ZIP upload'), ('star', 'Star'), ('fork', 'Fork'), ('milestone', 'Milestone'), ('achievement', 'Achievement'), ('git_push_rejected', 'Git push rejected'), ('approval', 'Approval needed'), ('pending', 'Pending approval'), ('review_needed', 'Review needed'), ('challenge_draft', 'Challenge draft'), ('role', 'Role'), ('account_quarantine', 'Account quarantine'), ('appeal', 'Quarantine appeal'), ('feedback', 'Feedback'), ('duplicate', 'Duplicate build'), ('malfunction', 'Malfunction')], max_length=20),
        ),
    ]
