# Generated by Django 5.2.17 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0047_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='publish_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Submission id of the publish request that created this row.', max_length=64),
        ),
    ]
