# Generated by Django 5.2.17 on 2026-10-01 21:47

from django.db import migrations, models


def protect_cache(apps, schema_editor):
    # Supabase exposes public-schema tables through its REST API. With no RLS
    # policies, anon/authenticated API roles cannot read cached private data.
    # The trusted Django database owner can still maintain its own table.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE blaqvibes_cache ENABLE ROW LEVEL SECURITY')


def unprotect_cache(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE blaqvibes_cache DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0048_appproject_publish_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'blaqvibes_cache',
            },
        ),
        migrations.RunPython(protect_cache, unprotect_cache),
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('scanning', 'Scanning'), ('pending', 'Awaiting review'), ('clean', 'Clean'), ('quarantined', 'Quarantined'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', 'created_at'], name='gallery_scan_queue_idx'),
        ),
    ]
